language: java

addons:
  apt:
    packages:
      - openjdk-6-jdk
os:
  #- osx
  - linux
jdk:
  - openjdk6
  - openjdk7
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
sudo: required
script: mvn clean install
