language: java

sudo: false
services:
  - docker
cache:
  directories:
    - $HOME/.m2

jobs:
  include:
    - os: linux
      jdk:
        - openjdk8
        - openjdk9
        - openjdk10
        - openjdk11
    - os: osx
      jdk:
        - openjdk9
        - openjdk10
        - openjdk11

script: mvn clean install
