language: java

sudo: false
services:
  - docker
cache:
  directories:
    - $HOME/.m2
#env:
#  - GPG_KEYNAME=$GPG_KEYNAME
#  - GPG_PASSPHRASE=$GPG_PASSPHRASE

jobs:
  include:
    - os: linux
      jdk: openjdk8
    - os: linux
      jdk: openjdk9
    - os: linux
      jdk: openjdk10
    - os: linux
      jdk: openjdk11
    - os: osx
      jdk: openjdk9
    - os: osx
      jdk: openjdk10
    - os: osx
      jdk: openjdk11

script: mvn clean install
