language: java

addons:
  apt:
    packages:
      - openjdk-6-jdk
      - openjdk-7-jdk
      - openjdk-8-jdk
os:
  - osx
  - linux
jdk:
  - openjdk6
  - openjdk7
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
sudo: false
script: mvn clean install
